# Generated by Django 4.1.5 on 2023-02-14 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_listings_contact_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 14, 11, 2, 17, 69790)),
        ),
    ]
